# rustfmt.toml

edition = "2021"

# Keep lines from wrapping so more stays inline
max_width = 999999
use_small_heuristics = "Max"

# Aggressively allow single-line constructs
where_single_line = true
trailing_comma = "Never"
match_block_trailing_comma = false

# Prefer everything on one line when it fits
array_width = 999
attr_fn_like_width = 999
fn_call_width = 999
struct_lit_width = 999
struct_variant_width = 999

# Braces on the next line (Allman-style)
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"

# Keep comments compact and avoid reflowing
wrap_comments = false
comment_width = 120
format_code_in_doc_comments = false
normalize_comments = false

# Reduce vertical whitespace
blank_lines_upper_bound = 2

# Consistent newlines
newline_style = "Unix"
